=== dell/omnia/input_validation/module_utils/schema/software_config.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "cluster_os_type": {
      "type": "string",
      "enum": ["ubuntu", "rhel", "rocky"],
      "description": "Specifies the type of operating system for the cluster."
    },
    "cluster_os_version": {
      "type": "string",
      "description": "Specifies the version of the operating system for the cluster."
    },
    "repo_config": {
      "type": "string",
      "enum": ["always", "partial"],
      "description": "Specifies how repository configurations are handled."
    },
    "softwares": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "version": { "type": "string" }
        },
        "required": ["name"]
      },
      "description": "Array of software packages to be configured."
    },
    "bcm_roce": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "version": { "type": "string" }
        },
        "required": ["name"]
      },
      "description": "Array of BCM RoCE libraries."
    },
    "amdgpu": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "version": { "type": "string" }
        },
        "required": ["name"]
      },
      "description": "Array of AMDGPU software components."
    },
    "pytorch": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" }
        },
        "required": ["name"]
      },
      "description": "Array of PyTorch components."
    },
    "tensorflow": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" }
        },
        "required": ["name"]
      },
      "description": "Array of TensorFlow components."
    },
    "intelgaudi": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" }
        },
        "required": ["name"]
      },
      "description": "Array of Intel Gaudi components."
    }
  },
  "required": ["cluster_os_type", "cluster_os_version", "repo_config", "softwares"]
}

=== dell/omnia/examples/ubuntu_software_config.json
{
    "cluster_os_type": "ubuntu",
    "cluster_os_version": "22.04",
    "repo_config": "partial",
    "softwares": [
        {"name": "amdgpu", "version": "6.0"},
        {"name": "bcm_roce", "version": "229.2.61.0"},
        {"name": "openldap"},
        {"name": "nfs"},
        {"name": "k8s", "version":"1.26.12"},
        {"name": "jupyter"},
        {"name": "pytorch"},
        {"name": "tensorflow"}
    ],

    "bcm_roce": [
        {"name": "bcm_roce_libraries", "version": "229.2.61.0"}
    ],
   "amdgpu": [
        {"name": "rocm", "version": "6.0" }
    ],
    "pytorch": [
        {"name": "pytorch_cpu"},
        {"name": "pytorch_amd"},
        {"name": "pytorch_nvidia"}
    ],
    "tensorflow": [
        {"name": "tensorflow_cpu"},
        {"name": "tensorflow_amd"},
        {"name": "tensorflow_nvidia"}
    ]

}

=== dell/omnia/examples/software_config_template/template_rhel_9.4_software_config.json
{
    "cluster_os_type": "rhel",
    "cluster_os_version": "9.4",
    "repo_config": "always",
    "softwares": [
        {"name": "amdgpu", "version": "6.3.1"},
        {"name": "cuda", "version": "12.5.0"},
        {"name": "ofed", "version": "24.10-1.1.4.0"},
        {"name": "freeipa"},
        {"name": "openldap"},
        {"name": "secure_login_node"},
        {"name": "nfs"},
        {"name": "beegfs", "version": "7.4.5"},
        {"name": "slurm"},
        {"name": "k8s", "version":"1.29.5"},
        {"name": "intel_benchmarks", "version": "2024.1.0"},
        {"name": "amd_benchmarks"},
        {"name": "utils"},
        {"name": "ucx", "version": "1.15.0"},
        {"name": "openmpi", "version": "4.1.6"},
        {"name": "csi_driver_powerscale", "version":"v2.11.0"}
    ],

    "amdgpu": [
        {"name": "rocm", "version": "6.3.1" }
    ]

}

=== dell/omnia/examples/rocky_software_config.json
{
    "cluster_os_type": "rocky",
    "cluster_os_version": "8.8",
    "repo_config": "partial",
    "softwares": [
        {"name": "amdgpu", "version": "6.0"},
        {"name": "cuda", "version": "12.3.2"},
        {"name": "ofed", "version": "24.01-0.3.3.1"},
        {"name": "openldap"},
        {"name": "nfs"},
        {"name": "slurm"},
        {"name": "k8s", "version":"1.26.12"},
        {"name": "jupyter"},
        {"name": "pytorch"},
        {"name": "tensorflow"}
    ],

    "amdgpu": [
        {"name": "rocm", "version": "6.0" }
    ],
    "pytorch": [
        {"name": "pytorch_cpu"},
        {"name": "pytorch_amd"},
        {"name": "pytorch_nvidia"}
    ],
    "tensorflow": [
        {"name": "tensorflow_cpu"},
        {"name": "tensorflow_amd"},
        {"name": "tensorflow_nvidia"}
    ]

}

=== dell/omnia/input/software_config.json
{
    "cluster_os_type": "ubuntu",
    "cluster_os_version": "22.04",
    "repo_config": "partial",
    "softwares": [
        {"name": "amdgpu", "version": "6.2.2"},
        {"name": "bcm_roce", "version": "230.2.54.0"},
        {"name": "openldap"},
        {"name": "nfs"},
        {"name": "k8s", "version":"1.29.5"},
        {"name": "roce_plugin"},
        {"name": "jupyter"},
        {"name": "pytorch"},
        {"name": "tensorflow"},
        {"name": "intelgaudi", "version": "1.19.1-26"}
    ],

    "bcm_roce": [
        {"name": "bcm_roce_libraries", "version": "230.2.54.0"}
    ],
   "amdgpu": [
        {"name": "rocm", "version": "6.2.2" }
    ],
   "intelgaudi": [
        {"name": "intel"}
    ],
    "pytorch": [
        {"name": "pytorch_cpu"},
        {"name": "pytorch_amd"},
        {"name": "pytorch_nvidia"},
        {"name": "pytorch_gaudi"}
    ],
    "tensorflow": [
        {"name": "tensorflow_cpu"},
        {"name": "tensorflow_amd"},
        {"name": "tensorflow_nvidia"}
    ]

}
